export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
};

export const Items = [
    {
        id: 122,
        category: 'product',
        productName: 'Tai nghe bluetooth E234',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 267000,
        rate: 4.49,
        buyCount: 678,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 156,
        category: 'product',
        productName: 'Tai nghe A222',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 3447,
        rate: 4.99,
        buyCount: 58,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 100,
        category: 'product',
        productName: 'Tai nghe DF33',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 2677,
        rate: 4.99,
        buyCount: 58,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 99,
        category: 'product',
        productName: 'MI Super Bass Bluetooth Wireless Headphones',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 1999,
        rate: 4.99,
        buyCount: 78,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 1,
        category: 'product',
        productName: 'Tai nghe Z111',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 2777,
        rate: 4.99,
        buyCount: 56,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 2,
        category: 'product',
        productName: 'Tai nghe OM 50401',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 2300,
        rate: 4.99,
        buyCount: 54,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        productImage: require('../database/images/products/boat1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/boat1.png'),
            require('../database/images/products/boat2.png'),
            require('../database/images/products/boat3.png'),
        ],
    },
    {
        id: 3,
        category: 'accessory',
        productName: 'boAt Airdopes 441',
        productPrice: 1999,
        rate: 4,
        buyCount: 5678,
        description:
            'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
        isOff: false,
        offPercentage: 18,
        productImage: require('../database/images/accessories/boatairpods1.png'),
        isAvailable: false,
        productImageList: [
            require('../database/images/accessories/boatairpods1.png'),
            require('../database/images/accessories/boatairpods2.png'),
            require('../database/images/accessories/boatairpods3.png'),
        ],
    },
    {
        id: 4,
        category: 'accessory',
        productName: 'boAt Bassheads 242',
        productPrice: 399,
        rate: 4,
        description:
            'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
        isOff: false,
        productImage: require('../database/images/accessories/boatbassheads1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/accessories/boatbassheads1.png'),
            require('../database/images/accessories/boatbassheads2.png'),
            require('../database/images/accessories/boatbassheads3.png'),
        ],
    },
    {
        id: 5,
        category: 'accessory',
        productName: 'boAt Rockerz 255 Pro+',
        productPrice: 1499,
        rate: 4,
        description:
            'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
        isOff: false,
        productImage: require('../database/images/accessories/boatrockerz1.png'),
        isAvailable: false,
        productImageList: [
            require('../database/images/accessories/boatrockerz1.png'),
            require('../database/images/accessories/boatrockerz2.png'),
            require('../database/images/accessories/boatrockerz3.png'),
        ],
    },
    {
        id: 6,
        category: 'accessory',
        productName: 'Boult Audio AirBass Propods TWS',
        productPrice: 1299,
        rate: 4.99,
        description:
            'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
        isOff: false,
        productImage: require('../database/images/accessories/boultairbass1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/accessories/boultairbass1.png'),
            require('../database/images/accessories/boultairbass2.png'),
            require('../database/images/accessories/boultairbass3.png'),
        ],
    },
    {
        id: 122,
        category: 'product',
        productName: 'Tai nghe bluetooth E234',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 267000,
        rate: 4.49,
        buyCount: 678,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 156,
        category: 'product',
        productName: 'Tai nghe A222',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 3447,
        rate: 4.99,
        buyCount: 58,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 100,
        category: 'product',
        productName: 'Tai nghe DF33',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 2677,
        rate: 4.99,
        buyCount: 58,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 99,
        category: 'product',
        productName: 'MI Super Bass Bluetooth Wireless Headphones',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 1999,
        rate: 4.99,
        buyCount: 78,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 1,
        category: 'product',
        productName: 'Tai nghe Z111',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 2777,
        rate: 4.99,
        buyCount: 56,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        offPercentage: 10,
        productImage: require('../database/images/products/Mi1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/Mi1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ],
    },
    {
        id: 2,
        category: 'product',
        productName: 'Tai nghe OM 50401',
        suppilerName: "Công ty thời số",
        suppilerAddress: "122, Nguyễn Văn Cừ nối dài, Cần Thơ",
        productPrice: 2300,
        rate: 4.99,
        buyCount: 54,
        description:
            'Thời lượng pin lên đến 20 giờ | Bass cực mạnh | Điếc cũng có thể nghe | Bluetooth 5.0 | Điều khiển giọng nói',
        isOff: false,
        productImage: require('../database/images/products/boat1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/products/boat1.png'),
            require('../database/images/products/boat2.png'),
            require('../database/images/products/boat3.png'),
        ],
    },
    {
        id: 3,
        category: 'accessory',
        productName: 'boAt Airdopes 441',
        productPrice: 1999,
        rate: 4,
        buyCount: 5678,
        description:
            'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
        isOff: false,
        offPercentage: 18,
        productImage: require('../database/images/accessories/boatairpods1.png'),
        isAvailable: false,
        productImageList: [
            require('../database/images/accessories/boatairpods1.png'),
            require('../database/images/accessories/boatairpods2.png'),
            require('../database/images/accessories/boatairpods3.png'),
        ],
    },
    {
        id: 4,
        category: 'accessory',
        productName: 'boAt Bassheads 242',
        productPrice: 399,
        rate: 4,
        description:
            'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
        isOff: false,
        productImage: require('../database/images/accessories/boatbassheads1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/accessories/boatbassheads1.png'),
            require('../database/images/accessories/boatbassheads2.png'),
            require('../database/images/accessories/boatbassheads3.png'),
        ],
    },
    {
        id: 5,
        category: 'accessory',
        productName: 'boAt Rockerz 255 Pro+',
        productPrice: 1499,
        rate: 4,
        description:
            'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
        isOff: false,
        productImage: require('../database/images/accessories/boatrockerz1.png'),
        isAvailable: false,
        productImageList: [
            require('../database/images/accessories/boatrockerz1.png'),
            require('../database/images/accessories/boatrockerz2.png'),
            require('../database/images/accessories/boatrockerz3.png'),
        ],
    },
    {
        id: 6,
        category: 'accessory',
        productName: 'Boult Audio AirBass Propods TWS',
        productPrice: 1299,
        rate: 4.99,
        description:
            'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
        isOff: false,
        productImage: require('../database/images/accessories/boultairbass1.png'),
        isAvailable: true,
        productImageList: [
            require('../database/images/accessories/boultairbass1.png'),
            require('../database/images/accessories/boultairbass2.png'),
            require('../database/images/accessories/boultairbass3.png'),
        ],
    },
]
